name: Build modules

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - naive-lemmatizer
          - naive-lemmatizer-less-prefixes 
        elastic: [6.2.3, 7.17.0] 
        java: ['11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -Delasticsearch.version=${{ matrix.elastic }} package
        working-directory: Sefaria-ElasticSearch-${{ matrix.module }}
      - name: Populate Properties File
        run: |
          cat << EOF > out/artifacts/elasticsearch/plugin-descriptor.properties
            name=analysis-sefaria-${{ matrix.module }}
            description=Sefaria analyzer powered by Noah
            classname=org.sefaria.sefariaplugin.plugin.SefariaPlugin
            elasticsearch.version=${{ matrix.elastic }}
            java.version=${{ matrix.java }}
            version=${{ matrix.elastic }}
            EOF
        working-directory: Sefaria-ElasticSearch-${{ matrix.module }}
      - name: Zip Plugin
        uses: thedoctor0/zip-release@0.7.0
        with:
          type: "zip"
          directory: Sefaria-ElasticSearch-${{ matrix.module }}/out/artifacts
          filename: ${{ matrix.module }}.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.module }}
          path: Sefaria-ElasticSearch-${{ matrix.module }}/out/artifacts/${{ matrix.module}}.zip 
