name: Build modules

on:
  push:
    tags:
      - v.*
  workflow_dispatch:

jobs:
  release:
    outputs:
      release: ${{ step.check.outputs.release }}
    steps:
      - name: Create release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: gh release create ${{ github.ref_name }} --latest --verify-tag
      - name: Get release name
        id: check
        run : echo release=$(gh release view --json name --jq .name) >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        module:
          - naive-lemmatizer
          - naive-lemmatizer-less-prefixes 
        elastic: [6.2.3, 7.17.0] 
        java: ['11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -Delasticsearch.version=${{ matrix.elastic }} -Dsefaria.version=${{ needs.release.outputs.release }} package
        working-directory: Sefaria-ElasticSearch-${{ matrix.module }}
      - name: Populate Properties File
        run: |
          cat << EOF > out/artifacts/elasticsearch/plugin-descriptor.properties
            name=analysis-sefaria-${{ matrix.module }}
            description=Sefaria analyzer powered by Noah
            classname=org.sefaria.sefariaplugin.plugin.SefariaPlugin
            elasticsearch.version=${{ matrix.elastic }}
            java.version=${{ matrix.java }}
            version=${{ needs.release.outputs.release }}
            EOF
        working-directory: Sefaria-ElasticSearch-${{ matrix.module }}
      - name: Zip Plugin
        uses: thedoctor0/zip-release@0.7.0
        with:
          type: "zip"
          directory: Sefaria-ElasticSearch-${{ matrix.module }}/out/artifacts
          filename: ${{ matrix.module }}-${{ needs.release.outputs.release }}-${{ matrix.elastic }}.zip
      - name: Upload artifact
        run: |
          cd Sefaria-ElasticSearch-${{ matrix.module }}/out/artifacts
          gh release upload ${{ needs.release.outputs.release }} '${{ matrix.module }}-${{ needs.release.outputs.release }}-${{ matrix.elastic }}.zip'
      - name: cleanup cache
        run: rm -rf *
        working-directory: Sefaria-ElasticSearch-${{ matrix.module }}/out/artifacts
  container:
    runs-on: ubuntu-latest
    needs: 
      - build
      - release
    strategy:
      matrix:
        elastic: [6.2.3, 7.17.0] 
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.PROD_GKE_SA_KEY }}
      - name: download plugins
        run: |
          gh release download --pattern '*-${{ matrix.elastic }}.zip'
      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            gcr.io/${{ secrets.DEV_PROJECT }}/sefaria-elasticsearch-${{ matrix.elastic }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=sha
            type=semver,pattern={{raw}},value=${{ needs.release.outputs.release }}
          flavor: |
            latest=true
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            PLUGIN_VERSION=${{  needs.release.outputs.release }}
            ELASTIC_VERSION=${{ matrix.elastic }}
          file: ./build/Sefaria/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

